apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glusterfs-storage
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://192.168.123.133:8080"
  restuser: "admin"
#  restuserkey: "heketi123"
  secretNamespace: "default"
  secretName: "heketi-secret"
allowVolumeExpansion:  True
